# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171218_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='You are only allowed to post charecters', max_length=5000),
        ),
    ]
