# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171220_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
